global:
  scrape_interval:     1s
  scrape_timeout:      1s
  evaluation_interval: 5s

scrape_configs:
  - job_name: mysql_hr
    scrape_interval:    1s
    scrape_timeout:     1s
    target_groups:
      - targets: ['DB_NODE_IP:9104']
        labels:
          alias: ts140i

  - job_name: mysql_mr
    scrape_interval:    5s
    scrape_timeout:     1s
    target_groups:
      - targets: ['DB_NODE_IP:9204']
        labels:
          alias: ts140i

  - job_name: mysql_lr
    scrape_interval:    60s
    scrape_timeout:     5s
    target_groups:
      - targets: ['DB_NODE_IP:9304']
        labels:
          alias: ts140i

  - job_name: linux
    target_groups:
      - targets: ['DB_NODE_IP:9100']
        labels:
          alias: ts140i

  - job_name: prometheus
    target_groups:
      - targets: ['localhost:9090']
        labels:
          alias: zts

